repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer

- repo: https://github.com/dnephin/pre-commit-golang
  rev: v0.5.1
  hooks:
    - id: go-fmt
      always_run: true
    - id: go-mod-tidy
      always_run: true

- repo: local
  hooks:
    - id: go-generate
      name: go generate
      entry: go generate ./...
      language: system
      pass_filenames: false
      types: [go]
