repos:
- repo: https://github.com/dnephin/pre-commit-golang
  rev: v0.5.1
  hooks:
    - id: go-fmt
    - id: go-mod-tidy

- repo: local
  hooks:
    - id: go-generate
      name: go generate
      entry: go generate ./...
      language: system
      pass_filenames: false
      types: [go]
