name: deploy
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACC_KEY }}
      
      - name: Configure gcloud
        run: |
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
          gcloud auth configure-docker us-docker.pkg.dev
          sudo apt-get install -y kubectl google-cloud-sdk-gke-gcloud-auth-plugin
          echo "USE_GKE_GCLOUD_AUTH_PLUGIN=True" >> $GITHUB_ENV
          gcloud container clusters get-credentials ${{ secrets.GCP_GKE_CLUSTER }} --region ${{ secrets.GCP_REGION }}
      
      - name: Build and Push Docker Image
        run: |
          docker build -t us-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/gridstream/batcher:${{ github.sha }} .
          docker push us-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/gridstream/batcher:${{ github.sha }}
      
      - name: Create K8s Secrets
        run: |
          kubectl create secret generic bigquery-credentials \
            --from-file=credentials.json=/dev/stdin \
            --dry-run=client -o yaml | kubectl apply -f -

          kubectl create secret generic batcher-config \
            --from-file=config.json=/dev/stdin \
            --dry-run=client -o yaml | kubectl apply -f -
        env:
          BIGQUERY_CREDS: ${{ secrets.CREDS_PATH_SECRET }}
          BATCHER_CONFIG: ${{ secrets.BATCHER_STREAM_CONFIG_SECRET }}

      - name: Update Deployment Image
        run: |
          kubectl set image deployment/batcher-stream \
            batcher=us-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/gridstream/batcher:${{ github.sha }}
          kubectl rollout status deployment/batcher-stream

  tag:
    name: tag
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Create tag
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}